package cadastrobd.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ConectorBD {

    private static final String URL = "jdbc:sqlserver://localhost:1433;databaseName=loja;encrypt=true;trustServerCertificate=true";
    private static final String USER = "loja";
    private static final String PASSWORD = "loja";

    // Método para obter uma conexão com o banco de dados
    public static Connection getConnection() throws SQLException {
        try {
            return DriverManager.getConnection(URL, USER, PASSWORD);
        } catch (SQLException e) {
            System.err.println("Erro ao tentar conectar ao banco de dados: " + e.getMessage());
            throw e;  // Repassa a exceção para tratamento externo
        }
    }

    // Método para preparar um statement
    public static PreparedStatement getPrepared(Connection conn, String sql) throws SQLException {
        return conn.prepareStatement(sql);
    }

    // Sobrecarga para obter PreparedStatement com suporte a chaves geradas
    public static PreparedStatement getPrepared(Connection conn, String sql, int autoGeneratedKeys) throws SQLException {
        return conn.prepareStatement(sql, autoGeneratedKeys);
    }

    // Método para executar um SELECT
    public static ResultSet getSelect(PreparedStatement stmt) throws SQLException {
        return stmt.executeQuery();
    }

    // Métodos para fechamento seguro de conexões e recursos
    public static void close(Connection conn) {
        closeResource(conn, "conexão");
    }

    public static void close(PreparedStatement stmt) {
        closeResource(stmt, "PreparedStatement");
    }

    public static void close(ResultSet rs) {
        closeResource(rs, "ResultSet");
    }

    // Método genérico para fechamento de recursos
    private static void closeResource(AutoCloseable resource, String resourceName) {
        if (resource != null) {
            try {
                resource.close();
            } catch (Exception e) {
                System.err.println("Erro ao fechar " + resourceName + ": " + e.getMessage());
            }
        }
    }
}
